#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "$shome/vendor/slate/vendor/bundle/bin/middleman" ]]; then
    return 0
  fi

  return 0
}

source sub "$0" "$@"
